### PR TITLE
function for final df 

### PR DESCRIPTION
**Pull request by ranawg**
created a script for creating the final data frame that gets fed to the model of wetChemAbsorbance, should we include it to the tidy_createDataFrameScript.R file?

### CODE REVIEW

**Review by DawningAventide — COMMENTED** [review]
You commented that some rows with scientific notation don't get parsed correctly and needed correction. Has that been corrected?

**Comment by ranawg** [comment]
Not yet, I think it has to be dealt with when first importing the script? but I will try a couple of things
  
​

**Review by hartlegr — COMMENTED** [review]
I'm a little confused about what this is doing that is different than the functions in tidy_createDataFrameScript in PR #49 , is it because it's Alaska specific?

**Comment by ranawg** [comment]
The first part is Alaska specific using the same process as vivianne's code.
  
​
  
​I meant the the function at lines 63-110 that should be general, that relates to the part where you suggested a possible streamlined process, so maybe I should put it in a different file. I used the Alaska sample to test the function.
  
​

**Comment by hartlegr** [comment]
Okay sounds good. I can't remember if I mentioned in slack but I spent awhile essentially trying to recreate the wheel and realized that a lot of vivienne's code is going to work best. The functions in #49 and looks like what you did are kinda just condensing that and are generalizable to the Alaska stuff!

**Pull request merged**
